routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ServiceController;


use App\Http\Controllers\SocialLoginController;

Auth::routes();

Route::get('/', [HomeController::class, 'index']);
Route::get('/home', [HomeController::class, 'index']);

Route::post('/products/{id}/purchase', [ProductController::class, 'purchase'])->name('products.purchase');
Route::post('/services/{id}/purchase', [ServiceController::class, 'purchase'])->name('services.purchase');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('services', ServiceController::class);
});

Route::get('auth/{provider}', [SocialLoginController::class, 'redirectToProvider'])
    ->name('auth')
    ->where('provider', implode('|', config('auth.socialite.drivers')));
Route::get('auth/{provider}/callback', [SocialLoginController::class, 'handleProviderCallback']);

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use App\Library\HttpResponse;
use App\Library\FileUpload;

class Service extends Model
{
    use HasFactory;

    protected $guarded = [];
    
    public function purchases(){
        return $this->MorphMany(Purchase::class, 'purchaseable');
    }

    public static function getServiceDetails()
    {
        return Service::latest()->simplePaginate(10);
    }

    public static function storeServiceDetails($serviceData)
    {
        Service::create($serviceData);
    }

    public static function updateServiceDetails($id, $serviceData)
    {
        Service::where('id', $id)->update($serviceData);
    }
    
    public static function destoryServiceDetails($id)
    {
        $services = Service::find($id);
        FileUpload::destory('services', $services->image);
        $services->delete();
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Library\FileUpload;
use App\Library\RazorpayPayment;
use App\Models\Service;
use App\Models\Payment;
use Illuminate\Http\Request;

class ServiceController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:service-list|service-create|service-edit|service-delete', ['only' => ['index','show']]);
        $this->middleware('permission:service-create', ['only' => ['create','store']]);
        $this->middleware('permission:service-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:service-delete', ['only' => ['destroy']]);
        $this->middleware('auth');
    }

    public function index()
    {
        $services = Service::getServiceDetails();
        return view('services.index',compact('services'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    public function create()
    {
        return view('services.create');
    }

    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
            'file' => 'image|mimes:jpg,jpeg,png,gif,svg|max:2048'
        ]);
        $image = $request->file('file');
        $fileName = '';
        if ($image) {
            $fileName = FileUpload::store('services', $image);
        }
        $serviceData = [
            'name' => $request->input('name'),
            'detail' => $request->input('detail'),
            'image' => $fileName
        ];
        Service::storeServiceDetails($serviceData);
        return redirect()->route('services.index')->with('success','Service created successfully.');
    }

    public function show(Service $service)
    {
        return view('services.show',compact('service'));
    }

    public function edit(Service $service)
    {
        return view('services.edit',compact('service'));
    }

    public function update(Request $request, Service $service)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
        $id = $service->id;
        $image = $request->file('file');
        $fileName = $request->input('oldFile');
        if ($image) {
            $OldFileName = $request->input('oldFile');
            $fileName = FileUpload::store('services', $image, $OldFileName);
        }
        $serviceData = [
            'name' => $request->input('name'),
            'detail' => $request->input('detail'),
            'image' => $fileName
        ];
        Service::updateServiceDetails($id, $serviceData);
        return redirect()->route('services.index')->with('success','Service updated successfully.');
    }

    public function destroy(Service $service)
    {
        Service::destoryServiceDetails($service->id);
        return redirect()->route('services.index')->with('success','Service deleted successfully.');
    }

    public function purchase(Request $request, $id)
    {
        $userId = auth()->user()->id;
        $input = $request->all();
        $payment = RazorpayPayment::store($input);
        $payInfo = [
            'productOrServiceId' => $id,
            'userId' => $userId,
            'razorpayPaymentId' => $payment['razorpay_payment_id'],
            'amount' => $payment['amount'],
            'type' => 'service',
        ];
        Payment::storePurchase($payInfo);
        return redirect()->route('services.index')->with('success','Service purchased successfully.');
    }
}

resources/views/services/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Service</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('services.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('services.store') }}" method="POST" enctype="multipart/form-data">
    	@csrf
         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Name:</strong>
		            <input type="text" name="name" class="form-control" placeholder="Name" value="{{ old('name') }}">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Image:</strong>
		            <input type="file" name="file" class="form-control" value="{{ old('file') }}">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Detail:</strong>
		            <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ old('detail') }}</textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
    </form>
@endsection

resources/views/services/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Service</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('services.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('services.update',$service->id) }}" method="POST" enctype="multipart/form-data">
    	@csrf
        @method('PUT')
         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Name:</strong>
		            <input type="text" name="name" value="{{ $service->name }}" class="form-control" placeholder="Name">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Image:</strong>
		            <input type="file" name="file" class="form-control">
		            <input type="hidden" name="oldFile" value="{{ $service->image }}" class="form-control">
                    <div id="file">@if($service->image)<img src="{{asset('storage/uploads/services/'.$service->image)}}" alt=" " style="width:150px; height:100px">@endif</div>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Detail:</strong>
		            <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ $service->detail }}</textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		      <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
    </form>
@endsection

resources/views/services/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Services</h2>
            </div>
            <div class="pull-right">
                @can('service-create')
                    <a class="btn btn-success" href="{{ route('services.create') }}"> Create New Service</a>
                @endcan
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
	    @foreach ($services as $service)
	    <tr>
	        <td>{{ ++$i }}</td>
	        <td>{{ $service->name }}</td>
	        <td>{{ $service->detail }}</td>
	        <td>
                <form action="{{ route('services.destroy',$service->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('services.show',$service->id) }}">Show</a>
                    @can('service-edit')
                        <a class="btn btn-primary" href="{{ route('services.edit',$service->id) }}">Edit</a>
                    @endcan
                    @csrf
                    @method('DELETE')
                    @can('service-delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    @endcan
                </form>
                <form action="{{ route('services.purchase', ['id' => $service->id]) }}" method="POST">
                    @csrf <br>
                    <script src="https://checkout.razorpay.com/v1/checkout.js"
                    data-key="rzp_test_ytr62VGcJ69Tlr"
                    data-amount="10000"
                    data-buttontext="Purchase"
                    data-name="TartLabs"
                    data-description="Razorpay"
                    data-image="https://cdn.tartlabs.com/wp-content/uploads/2019/02/B4FEFF78-93DB-4C4B-A8E1-6C98E4F8FDA9.png"
                    data-prefill.name=""
                    data-prefill.email=""
                    data-theme.color="#ff7529">
                    </script>
                </form>
                </form>
	        </td>
	    </tr>
	    @endforeach
    </table>
    {!! $services->links() !!}
@endsection

resources/views/services/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Service Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('services.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $service->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $service->detail }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Image:</strong>
                @if($service->image)<img src="{{asset('storage/uploads/services/'.$service->image)}}" alt=" " style="width:150px; height:100px">@endif
            </div>
        </div>
    </div>
@endsection