routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ServiceController;


use App\Http\Controllers\SocialLoginController;

Auth::routes();

Route::get('/', [HomeController::class, 'index']);
Route::get('/home', [HomeController::class, 'index']);

Route::post('/products/{id}/purchase', [ProductController::class, 'purchase'])->name('products.purchase');
Route::post('/services/{id}/purchase', [ServiceController::class, 'purchase'])->name('services.purchase');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);
    Route::resource('services', ServiceController::class);
});

Route::get('auth/{provider}', [SocialLoginController::class, 'redirectToProvider'])
    ->name('auth')
    ->where('provider', implode('|', config('auth.socialite.drivers')));
Route::get('auth/{provider}/callback', [SocialLoginController::class, 'handleProviderCallback']);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use App\Library\HttpResponse;
use App\Library\FileUpload;

class Product extends Model
{
    use HasFactory;

    protected $guarded = [];
    
    public function purchases(){
        return $this->MorphMany(Purchase::class, 'purchaseable');
    }

    public static function getProductDetails()
    {
        return Product::latest()->simplePaginate(10);
    }

    public static function storeProductDetails($productData)
    {
        Product::create($productData);
    }

    public static function updateProductDetails($id, $productData)
    {
        Product::where('id', $id)->update($productData);
    }
    
    public static function destoryProductDetails($id)
    {
        $products = Product::find($id);
        FileUpload::destory('products', $products->image);
        $products->delete();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Library\FileUpload;
use App\Library\RazorpayPayment;
use App\Models\Product;
use App\Models\Payment;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:product-list|product-create|product-edit|product-delete', ['only' => ['index','show']]);
        $this->middleware('permission:product-create', ['only' => ['create','store']]);
        $this->middleware('permission:product-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:product-delete', ['only' => ['destroy']]);
        $this->middleware('auth');
    }

    public function index()
    {
        $products = Product::getProductDetails();
        return view('products.index',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    public function create()
    {
        return view('products.create');
    }

    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
            'file' => 'image|mimes:jpg,jpeg,png,gif,svg|max:2048'
        ]);
        $image = $request->file('file');
        $fileName = '';
        if ($image) {
            $fileName = FileUpload::store('products', $image);
        }
        $productData = [
            'name' => $request->input('name'),
            'detail' => $request->input('detail'),
            'image' => $fileName
        ];
        Product::storeProductDetails($productData);
        return redirect()->route('products.index')->with('success','Product created successfully.');
    }

    public function show(Product $product)
    {
        return view('products.show',compact('product'));
    }

    public function edit(Product $product)
    {
        return view('products.edit',compact('product'));
    }

    public function update(Request $request, Product $product)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);
        $id = $product->id;
        $image = $request->file('file');
        $fileName = $request->input('oldFile');
        if ($image) {
            $OldFileName = $request->input('oldFile');
            $fileName = FileUpload::store('products', $image, $OldFileName);
        }
        $productData = [
            'name' => $request->input('name'),
            'detail' => $request->input('detail'),
            'image' => $fileName
        ];
        Product::updateProductDetails($id, $productData);
        return redirect()->route('products.index')->with('success','Product updated successfully.');
    }

    public function destroy(Product $product)
    {
        Product::destoryProductDetails($product->id);
        return redirect()->route('products.index')->with('success','Product deleted successfully.');
    }

    public function purchase(Request $request, $id)
    {
        $userId = auth()->user()->id;
        $input = $request->all();
        $payment = RazorpayPayment::store($input);
        $payInfo = [
            'productOrServiceId' => $id,
            'userId' => $userId,
            'razorpayPaymentId' => $payment['razorpay_payment_id'],
            'amount' => $payment['amount'],
            'type' => 'product',
        ];
        Payment::storePurchase($payInfo);
        return redirect()->route('products.index')->with('success','Product purchased successfully.');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
    	@csrf
         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Name:</strong>
		            <input type="text" name="name" class="form-control" placeholder="Name" value="{{ old('name') }}">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Image:</strong>
		            <input type="file" name="file" class="form-control">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Detail:</strong>
		            <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ old('detail') }}</textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
    </form>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('products.update',$product->id) }}" method="POST" enctype="multipart/form-data">
    	@csrf
        @method('PUT')
         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Name:</strong>
		            <input type="text" name="name" value="{{ $product->name }}" class="form-control" placeholder="Name">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Image:</strong>
		            <input type="file" name="file" class="form-control">
		            <input type="hidden" name="oldFile" value="{{ $product->image }}" class="form-control">
                    <div id="file">@if($product->image)<img src="{{asset('storage/uploads/products/'.$product->image)}}" alt=" " style="width:150px; height:100px">@endif</div>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Detail:</strong>
		            <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ $product->detail }}</textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		      <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
    </form>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Products</h2>
            </div>
            <div class="pull-right">
                @can('product-create')
                    <a class="btn btn-success" href="{{ route('products.create') }}"> Create New Product</a>
                @endcan
            </div>
        </div>
    </div>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
	    @foreach ($products as $product)
	    <tr>
	        <td>{{ ++$i }}</td>
	        <td>{{ $product->name }}</td>
	        <td>{{ $product->detail }}</td>
	        <td>
                <form action="{{ route('products.destroy',$product->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('products.show', $product->id) }}">Show</a>
                    @can('product-edit')
                        <a class="btn btn-primary" href="{{ route('products.edit', $product->id) }}">Edit</a>
                    @endcan
                    @csrf
                    @method('DELETE')
                    @can('product-delete')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    @endcan
                </form>
                <form action="{{ route('products.purchase', ['id' => $product->id]) }}" method="POST">
                    @csrf <br>
                    <script src="https://checkout.razorpay.com/v1/checkout.js"
                    data-key="rzp_test_ytr62VGcJ69Tlr"
                    data-amount="10000"
                    data-buttontext="Purchase"
                    data-name="TartLabs"
                    data-description="Razorpay"
                    data-image="https://cdn.tartlabs.com/wp-content/uploads/2019/02/B4FEFF78-93DB-4C4B-A8E1-6C98E4F8FDA9.png"
                    data-prefill.name=""
                    data-prefill.email=""
                    data-theme.color="#ff7529">
                    </script>
                </form>
	        </td>
	    </tr>
	    @endforeach
    </table>
    {!! $products->links() !!}
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Product Details</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('products.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $product->detail }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Image:</strong>
                @if($product->image)<img src="{{asset('storage/uploads/products/'.$product->image)}}" alt=" " style="width:150px; height:100px">@endif
            </div>
        </div>
    </div>
@endsection